import type { Metadata } from "next";
import { Geist, Geist_Mono, Bitter} from "next/font/google";
import "./globals.css";

import NavMain from "@/components/navigation/nav-main";//nya code 12feb

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const bitterFont = Bitter({
  variable: "--font-bitter",
  subsets: ["latin"],
  weight: ["800"],
});

/*const roboto = Roboto({
  variable: "--font-roboto",
  weight: ["400"],
});

const islandMoments = Island_Moments({
  variable: "--font-island-moment",
  weight: ["400"],
});*//*

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/*export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${bitterFont.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}*/ //den i 11feb

//den nya i 12 feb

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${bitterFont.variable}`}>
        <NavMain />
        {children}
      </body>
    </html>
  );
}