import type { Metadata } from "next";
import { Geist, Geist_Mono, Bitter} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const bitterFont = Bitter({
  variable: "--font-bitter",
  subsets: ["latin"],
  weight: ["800"],
});

/*const roboto = Roboto({
  variable: "--font-roboto",
  weight: ["400"],
});

const islandMoments = Island_Moments({
  variable: "--font-island-moment",
  weight: ["400"],
});*/

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${bitterFont.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
